language: node_js
os: linux
dist: trusty
node_js:
  - 8
  - 10
addons:
  firefox: latest
  apt:
    packages:
    - google-chrome-stable
    # TODO (#2114): reenable osx build.
    # - os: osx
    #   node_js: stable
    #   osx_image: xcode8.3
    #   addons:
    #     firefox: latest

before_script:
  # Symlink closure library used by test/jsunit
  - ln -s $(npm root)/google-closure-library ../closure-library
  - export DISPLAY=:99.0
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then ( tests/scripts/setup_linux_env.sh ) fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then ( tests/scripts/setup_osx_env.sh ) fi
  - sleep 2

script:
  - tests/run_all_tests.sh
