contact_links:
  - name: Ask a question â“
    url: https://groups.google.com/forum/#!forum/blockly
    about: Go to the Blockly developer forum, where you can ask and answer questions.
  - name: Report issues with plugins and examples ğŸ§©
    url: https://github.com/google/blockly-samples/issues/new/choose
    about: File bugs or feature requests about plugins and samples in our blockly-samples repository.
